### ISSUE TITLE
Can't find docs or examples for toml files

### ISSUE THREAD

**Issue by sa-** [drgarcia1986/simple-settings#289]
As the title explains, I can't seem to find the docs for this package or an example of how to use toml files. It would be nice if this information was easy to find

**Comment by drgarcia1986** [comment]
Hm, maybe something like this?

```python
# app.py
from simple_settings import settings

print(settings.simple)
print(settings.complex)
print(settings.complex['text'])
```
```toml
# settings.toml
simple = "a simple string"

[complex]
text = "this is a text in a complex struct"
```
```sh
$ SIMPLE_SETTINGS=settings.toml python app.py
a simple string
{'text': 'this is a text in a complex struct'}
this is a text in a complex struct
```
