### ISSUE TITLE
Required settings and OVERRIDE_BY_ENV: True

### ISSUE THREAD

**Issue by aensidhe** [drgarcia1986/simple-settings#59]
E.g. I have such config:
```yaml
SIMPLE_SETTINGS:
  OVERRIDE_BY_ENV: True
  REQUIRED_SETTINGS:
    - TeamcityBuildBranch
```

If I set later `TeamcityBuildBranch` environment variable to some not-null value, I'll get this error:
```python3
Traceback (most recent call last):
  File "./service_builder.py", line 247, in <module>
    main()
  File "./service_builder.py", line 224, in main
    settings.TeamcityBuildBranch.replace('/', '-'),
AttributeError: 'NoneType' object has no attribute 'replace'
```

I expect that if environment variable is set then we'll get no error and that value from environment variable.

**Comment by drgarcia1986** [comment]
Hum, I think `REQUIRED_SETTINGS` and `OVERRIDE_BY_ENV` don't work together, because `OVERRIDE_BY_ENV` only works for declared settings.

**Comment by aensidhe** [comment]
Can we count required settings as declared? :) I want to have script without default config, because I can't set reasonable defaults for some settings.

**Comment by drgarcia1986** [comment]
Let's take one thing at a time.

You can create a script without default configs and set some them as required with `REQUIRED_SETTINGS`, e.g.:

```yaml
# s.yaml
SIMPLE_SETTINGS:
  REQUIRED_SETTINGS:
    - TeamcityBuildBranch
```

```python
# app.py
from simple_settings import settings

try:
    settings.setup()
except ValueError as e:
    print(e)
```

```
$ SIMPLE_SETTINGS=s.yaml python app.py
The following settings are required: TeamcityBuildBranch
```

But you can't set value for this config only with an environment variable:
```
$ SIMPLE_SETTINGS=s.yaml TeamcityBuildBranch=foo python app.py
The following settings are required: TeamcityBuildBranch
```

Even if you use `OVERRIDE_BY_ENV` special settings:
```yaml
# s.yaml
SIMPLE_SETTINGS:
  OVERRIDE_BY_ENV: True
  REQUIRED_SETTINGS:
    - TeamcityBuildBranch
```
```
$ SIMPLE_SETTINGS=s.yaml TeamcityBuildBranch=foo python app.py
The following settings are required: TeamcityBuildBranch
```
Maybe ["load multiple settings modules"](http://simple-settings.readthedocs.io/en/latest/#load-multiple-settings-modules) can helping you, e.g:

```yaml
# s.yaml
SIMPLE_SETTINGS:
  REQUIRED_SETTINGS:
    - TeamcityBuildBranch
```
```yaml
# x.yaml
TeamcityBuildBranch: "Foo"
```
```python
# app.py
from simple_settings import settings

try:
    settings.setup()
except ValueError as e:
    print(e)

print(settings.TeamcityBuildBranch)
```
```
$ SIMPLE_SETTINGS=s.yaml,x.yaml python app.py
Foo
```
(Another way is to create something like "settings validators", but it's a feature request 😄 )
